### ISSUE TITLE
Tome Rater Review

### ISSUE THREAD

**Issue by franfranfranfran** [finn59/pwp-capstones#1]
### Criteria 1: Valid Python Code
* _Score Level:_ 4
* _Comment(s):_ Ah, so close. Most of the code runs great without any errors. The one test that does not pass is the most_read_book. Make sure you are calling the correct method name. Overall though, nice job testing out your code using the populate file and with including some nice descriptive comments throughout.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4
* _Comment(s):_ Great work implementing most of the project requirements. For the highest_rated_book method, nice job including the note to yourself and others that it does not currently work. This small bit of info can be really helpful when continuing work yourself, or sharing the project to work on with other people. As far as a fix - double check your indentation for the [return line](https://github.com/finn59/pwp-capstones/blob/master/for%20review/TomeRater.py#L92). I believe the best book should be returned after the whole for loop runs. 
 
### Criteria 3: Software Architecture
* _Score Level:_ 4
* _Comment(s):_ Code is separated into distinct classes and functions each which are invoked for their own purposes. Classes and their methods work together in clear and concise way. 
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 3
* _Comment(s):_ Nice job using various built-in python features throughout. Consider using the [format method](https://www.geeksforgeeks.org/python-format-function/) to help add in the bits of variable info into those printed strings. Also, consider streamlining various sections by returning right away instead of creating new variables. Here are a [couple](https://github.com/finn59/pwp-capstones/blob/master/for%20review/TomeRater.py#L142-L145) [examples](https://github.com/finn59/pwp-capstones/blob/master/for%20review/TomeRater.py#L32-L33). 
 
### Overall Score: 15/16
Nice work on this project. With a few small tweaks, everything will be looking perfect. As a next step, check out the info I included for the format method and try changing your printed strings to include that. 
Have fun and keep up the good work!

**Comment by finn59** [comment]
Hi
Thanks for your fast reply.
Actually i didn't see the problem you mention in criteria 1, as i made my own tests, and not the ones in populate.py script (that had to be un-commented).
If you see the attached screenshot from instructions sheet, we are instructed to name the method :  most_read_book, and i used that name for testing. So in other words, the last line line for testing in the populate.py "print(Tome_Rater.get_most_read_book())" is not correct according to the instructions sheet.
I checked the solution/fix mentioned in criteria 2 - and it works now :-)
I see your point in criteria 4, as i haven't being using the format command and i know the code could be smaller / lighter by returning directly.
Best regards
Finn Busk
![most_read_book](https://user-images.githubusercontent.com/44480682/50739952-4ee10c80-11e7-11e9-8850-fed12c7998a9.jpg)

**Comment by finn59** [comment]
done for now
